### ISSUE TITLE
Smaller Window

### ISSUE THREAD

**Issue by OllmGrb** [Maarten-vd-Sande/smoothed-particle-hydrodynamics#1]
Hi, firstly I would like to thank you for the incredible work you've done.

I am working on implementing an sph algorithm, and your work has greatly helped.
The only issue, I will be displaying the results of this algorithm on an LED matrix, hence I am bound to a 64x64 window. I first tried reducing the simulation window's width, height and limits, however I run into an error whereby dens[i] remains zero, which causes a divide by zero in the integration script. 
 I traced dens[i] back to the if condition r_2 <= h_2 in compute density pressure, and have determined that the if condition was never satisfied, and so dens[i] remains zero, causing problems later on.
My next instinct was to increase the radius, h, in order to 'force' the if condition. If i set it larger than 63, I get list index out of range (obviously), setting it less I remain with the error above.

Any further suggestions would be greatly appreciated, thanks.

![Screenshot_10](https://user-images.githubusercontent.com/55553672/80215497-d781f700-863c-11ea-8803-842b4e0b0090.png)
![Screenshot_11](https://user-images.githubusercontent.com/55553672/80215502-d8b32400-863c-11ea-9d18-3ef791637751.png)

**Comment by Maarten-vd-Sande** [comment]
I'm happy it helped :). I haven't looked at the code for over a year, so this does not immediately ring a bell to me. 

I will see if I have time to take a look at it somewhere after the weekend.

**Comment by Maarten-vd-Sande** [comment]
@OllmGrb  I made some changes, these should fix your issues.

Let me know if that works. Feel free to post a message showing the final result, sounds like a cool (but complicated) project :).

**Comment by OllmGrb** [comment]
Wow, thanks for the quick reply. Yes the changes worked, love the idea of the user-set error. I was wondering if you could help me grasp the matplot section. to my understanding, after each iteration of the animation function, the particles are plotted, and all the changes are then turned into an animation, correct? 
thanks again for your help.

**Comment by Maarten-vd-Sande** [comment]
Yes that is correct. I just use the matplotlib funcanimation for that: https://matplotlib.org/api/_as_gen/matplotlib.animation.FuncAnimation.html

I was thinking about your issue with the low Res led screen, and it shouldn't really depend on the width and height of the simulation. You will have to find a way to convert a list of coordinates for the particles or a (matplotlib) image into a 64*64 resolution. But at least now changing the params is a bit more robust.

**Comment by OllmGrb** [comment]
Just curious, how did u save the output in gif format? cheers

**Comment by Maarten-vd-Sande** [comment]
I think I converted the mp4 to gif
